version: "3" 

services:
  web:
    container_name: "web"
    build:
      dockerfile: "./nginx/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"

  php:
    container_name: "php"
    build:
      dockerfile: "./php/Dockerfile"
    volumes:
      - "./src:/var/www/html"

  db:
    container_name: "db"
    build:
      dockerfile: "./db/Dockerfile"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    volumes:
      - "./db/data:/var/lib/mysql"
